spring.application.name=ecom-proj

# Use file-based H2 (persists data)
spring.datasource.url=jdbc:h2:file:./data/ecommerce
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Run data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server port
server.port=${PORT:8080}